# Generated by Django 5.1.2 on 2024-11-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_whishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlist',
            old_name='product_id',
            new_name='pro_id',
        ),
        migrations.RenameField(
            model_name='whishlist',
            old_name='user_id',
            new_name='use_id',
        ),
    ]
