# Generated by Django 5.1.2 on 2024-11-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_product_id_whishlist_pro_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlist',
            old_name='pro_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='whishlist',
            old_name='use_id',
            new_name='user_id',
        ),
    ]
