# Generated by Django 5.1.2 on 2024-11-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogory',
            new_name='category',
        ),
    ]
