# Generated by Django 5.1.2 on 2024-11-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart'),
        ),
    ]
