# Generated by Django 5.1.2 on 2024-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
