# Generated by Django 5.1.2 on 2024-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_color_remove_product_color_alter_size_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
